server.port = 9002

#Mongo DB configuration
spring.data.mongodb.host=${DOCKER_MONGODB_HOSTNAME:localhost}
spring.data.mongodb.port=${DOCKER_MONGODB_PORT:27017}
spring.data.mongodb.database=noteDB

# Eureka Configuration
eureka.client.serviceUrl.defaultZone = http://${DOCKER_EUREKA_HOSTNAME:localhost}:9102/eureka/